// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/handlerzzy/feedsystem/internal/ai (interfaces: EmbeddingClient)
//
// Generated by this command:
//
//	mockgen -destination=mock/embedding_mock.go -package=mock github.com/handlerzzy/feedsystem/internal/ai EmbeddingClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	ai "github.com/handlerzzy/feedsystem/internal/ai"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmbeddingClient is a mock of EmbeddingClient interface.
type MockEmbeddingClient struct {
	ctrl     *gomock.Controller
	recorder *MockEmbeddingClientMockRecorder
	isgomock struct{}
}

// MockEmbeddingClientMockRecorder is the mock recorder for MockEmbeddingClient.
type MockEmbeddingClientMockRecorder struct {
	mock *MockEmbeddingClient
}

// NewMockEmbeddingClient creates a new mock instance.
func NewMockEmbeddingClient(ctrl *gomock.Controller) *MockEmbeddingClient {
	mock := &MockEmbeddingClient{ctrl: ctrl}
	mock.recorder = &MockEmbeddingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbeddingClient) EXPECT() *MockEmbeddingClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEmbeddingClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEmbeddingClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEmbeddingClient)(nil).Close))
}

// Embed mocks base method.
func (m *MockEmbeddingClient) Embed(ctx context.Context, req ai.EmbeddingRequest) (ai.EmbeddingResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Embed", ctx, req)
	ret0, _ := ret[0].(ai.EmbeddingResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Embed indicates an expected call of Embed.
func (mr *MockEmbeddingClientMockRecorder) Embed(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Embed", reflect.TypeOf((*MockEmbeddingClient)(nil).Embed), ctx, req)
}

// Health mocks base method.
func (m *MockEmbeddingClient) Health(ctx context.Context) (ai.EmbeddingHealth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", ctx)
	ret0, _ := ret[0].(ai.EmbeddingHealth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Health indicates an expected call of Health.
func (mr *MockEmbeddingClientMockRecorder) Health(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockEmbeddingClient)(nil).Health), ctx)
}
