// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/handlerzzy/feedsystem/internal/feed (interfaces: FeedStore)
//
// Generated by this command:
//
//	mockgen -destination=mock/feed_store_mock.go -package=mock github.com/handlerzzy/feedsystem/internal/feed FeedStore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	feed "github.com/handlerzzy/feedsystem/internal/feed"
	video "github.com/handlerzzy/feedsystem/internal/video"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockFeedStore is a mock of FeedStore interface.
type MockFeedStore struct {
	ctrl     *gomock.Controller
	recorder *MockFeedStoreMockRecorder
	isgomock struct{}
}

// MockFeedStoreMockRecorder is the mock recorder for MockFeedStore.
type MockFeedStoreMockRecorder struct {
	mock *MockFeedStore
}

// NewMockFeedStore creates a new mock instance.
func NewMockFeedStore(ctrl *gomock.Controller) *MockFeedStore {
	mock := &MockFeedStore{ctrl: ctrl}
	mock.recorder = &MockFeedStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedStore) EXPECT() *MockFeedStoreMockRecorder {
	return m.recorder
}

// GetByIDs mocks base method.
func (m *MockFeedStore) GetByIDs(ctx context.Context, ids []uint) ([]*video.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", ctx, ids)
	ret0, _ := ret[0].([]*video.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs.
func (mr *MockFeedStoreMockRecorder) GetByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockFeedStore)(nil).GetByIDs), ctx, ids)
}

// ListByFollowing mocks base method.
func (m *MockFeedStore) ListByFollowing(ctx context.Context, limit int, viewerAccountID uint, latestBefore time.Time) ([]*video.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByFollowing", ctx, limit, viewerAccountID, latestBefore)
	ret0, _ := ret[0].([]*video.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByFollowing indicates an expected call of ListByFollowing.
func (mr *MockFeedStoreMockRecorder) ListByFollowing(ctx, limit, viewerAccountID, latestBefore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByFollowing", reflect.TypeOf((*MockFeedStore)(nil).ListByFollowing), ctx, limit, viewerAccountID, latestBefore)
}

// ListByPopularity mocks base method.
func (m *MockFeedStore) ListByPopularity(ctx context.Context, limit int, popularityBefore int64, timeBefore time.Time, idBefore uint) ([]*video.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPopularity", ctx, limit, popularityBefore, timeBefore, idBefore)
	ret0, _ := ret[0].([]*video.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPopularity indicates an expected call of ListByPopularity.
func (mr *MockFeedStoreMockRecorder) ListByPopularity(ctx, limit, popularityBefore, timeBefore, idBefore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPopularity", reflect.TypeOf((*MockFeedStore)(nil).ListByPopularity), ctx, limit, popularityBefore, timeBefore, idBefore)
}

// ListByTag mocks base method.
func (m *MockFeedStore) ListByTag(ctx context.Context, tagName string, limit int) ([]*video.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTag", ctx, tagName, limit)
	ret0, _ := ret[0].([]*video.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTag indicates an expected call of ListByTag.
func (mr *MockFeedStoreMockRecorder) ListByTag(ctx, tagName, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTag", reflect.TypeOf((*MockFeedStore)(nil).ListByTag), ctx, tagName, limit)
}

// ListFreshLowEngagement mocks base method.
func (m *MockFeedStore) ListFreshLowEngagement(ctx context.Context, limit int, freshness time.Duration, maxPopularity int64, excludeAuthorID uint) ([]*video.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFreshLowEngagement", ctx, limit, freshness, maxPopularity, excludeAuthorID)
	ret0, _ := ret[0].([]*video.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFreshLowEngagement indicates an expected call of ListFreshLowEngagement.
func (mr *MockFeedStoreMockRecorder) ListFreshLowEngagement(ctx, limit, freshness, maxPopularity, excludeAuthorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFreshLowEngagement", reflect.TypeOf((*MockFeedStore)(nil).ListFreshLowEngagement), ctx, limit, freshness, maxPopularity, excludeAuthorID)
}

// ListLatest mocks base method.
func (m *MockFeedStore) ListLatest(ctx context.Context, limit int, latestBefore time.Time) ([]*video.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLatest", ctx, limit, latestBefore)
	ret0, _ := ret[0].([]*video.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLatest indicates an expected call of ListLatest.
func (mr *MockFeedStoreMockRecorder) ListLatest(ctx, limit, latestBefore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLatest", reflect.TypeOf((*MockFeedStore)(nil).ListLatest), ctx, limit, latestBefore)
}

// ListLikesCountWithCursor mocks base method.
func (m *MockFeedStore) ListLikesCountWithCursor(ctx context.Context, limit int, cursor *feed.LikesCountCursor) ([]*video.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLikesCountWithCursor", ctx, limit, cursor)
	ret0, _ := ret[0].([]*video.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLikesCountWithCursor indicates an expected call of ListLikesCountWithCursor.
func (mr *MockFeedStoreMockRecorder) ListLikesCountWithCursor(ctx, limit, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLikesCountWithCursor", reflect.TypeOf((*MockFeedStore)(nil).ListLikesCountWithCursor), ctx, limit, cursor)
}
