// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/handlerzzy/feedsystem/internal/feed (interfaces: LikeLookup)
//
// Generated by this command:
//
//	mockgen -destination=mock/like_lookup_mock.go -package=mock github.com/handlerzzy/feedsystem/internal/feed LikeLookup
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLikeLookup is a mock of LikeLookup interface.
type MockLikeLookup struct {
	ctrl     *gomock.Controller
	recorder *MockLikeLookupMockRecorder
	isgomock struct{}
}

// MockLikeLookupMockRecorder is the mock recorder for MockLikeLookup.
type MockLikeLookupMockRecorder struct {
	mock *MockLikeLookup
}

// NewMockLikeLookup creates a new mock instance.
func NewMockLikeLookup(ctrl *gomock.Controller) *MockLikeLookup {
	mock := &MockLikeLookup{ctrl: ctrl}
	mock.recorder = &MockLikeLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikeLookup) EXPECT() *MockLikeLookupMockRecorder {
	return m.recorder
}

// BatchGetLiked mocks base method.
func (m *MockLikeLookup) BatchGetLiked(ctx context.Context, videoIDs []uint, accountID uint) (map[uint]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetLiked", ctx, videoIDs, accountID)
	ret0, _ := ret[0].(map[uint]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetLiked indicates an expected call of BatchGetLiked.
func (mr *MockLikeLookupMockRecorder) BatchGetLiked(ctx, videoIDs, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetLiked", reflect.TypeOf((*MockLikeLookup)(nil).BatchGetLiked), ctx, videoIDs, accountID)
}
