// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/handlerzzy/feedsystem/internal/feed (interfaces: SummaryLookup)
//
// Generated by this command:
//
//	mockgen -destination=mock/summary_lookup_mock.go -package=mock github.com/handlerzzy/feedsystem/internal/feed SummaryLookup
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSummaryLookup is a mock of SummaryLookup interface.
type MockSummaryLookup struct {
	ctrl     *gomock.Controller
	recorder *MockSummaryLookupMockRecorder
	isgomock struct{}
}

// MockSummaryLookupMockRecorder is the mock recorder for MockSummaryLookup.
type MockSummaryLookupMockRecorder struct {
	mock *MockSummaryLookup
}

// NewMockSummaryLookup creates a new mock instance.
func NewMockSummaryLookup(ctrl *gomock.Controller) *MockSummaryLookup {
	mock := &MockSummaryLookup{ctrl: ctrl}
	mock.recorder = &MockSummaryLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSummaryLookup) EXPECT() *MockSummaryLookupMockRecorder {
	return m.recorder
}

// LatestAISummaries mocks base method.
func (m *MockSummaryLookup) LatestAISummaries(ctx context.Context, videoIDs []uint) (map[uint]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestAISummaries", ctx, videoIDs)
	ret0, _ := ret[0].(map[uint]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestAISummaries indicates an expected call of LatestAISummaries.
func (mr *MockSummaryLookupMockRecorder) LatestAISummaries(ctx, videoIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestAISummaries", reflect.TypeOf((*MockSummaryLookup)(nil).LatestAISummaries), ctx, videoIDs)
}
