// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/handlerzzy/feedsystem/internal/feed (interfaces: VectorRecallStore)
//
// Generated by this command:
//
//	mockgen -destination=mock/vector_recall_store_mock.go -package=mock github.com/handlerzzy/feedsystem/internal/feed VectorRecallStore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	video "github.com/handlerzzy/feedsystem/internal/video"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVectorRecallStore is a mock of VectorRecallStore interface.
type MockVectorRecallStore struct {
	ctrl     *gomock.Controller
	recorder *MockVectorRecallStoreMockRecorder
	isgomock struct{}
}

// MockVectorRecallStoreMockRecorder is the mock recorder for MockVectorRecallStore.
type MockVectorRecallStoreMockRecorder struct {
	mock *MockVectorRecallStore
}

// NewMockVectorRecallStore creates a new mock instance.
func NewMockVectorRecallStore(ctrl *gomock.Controller) *MockVectorRecallStore {
	mock := &MockVectorRecallStore{ctrl: ctrl}
	mock.recorder = &MockVectorRecallStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVectorRecallStore) EXPECT() *MockVectorRecallStoreMockRecorder {
	return m.recorder
}

// ListVectorCandidates mocks base method.
func (m *MockVectorRecallStore) ListVectorCandidates(ctx context.Context, model string, dim, limit int) ([]video.VectorCandidate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVectorCandidates", ctx, model, dim, limit)
	ret0, _ := ret[0].([]video.VectorCandidate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVectorCandidates indicates an expected call of ListVectorCandidates.
func (mr *MockVectorRecallStoreMockRecorder) ListVectorCandidates(ctx, model, dim, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVectorCandidates", reflect.TypeOf((*MockVectorRecallStore)(nil).ListVectorCandidates), ctx, model, dim, limit)
}

// LoadVectors mocks base method.
func (m *MockVectorRecallStore) LoadVectors(ctx context.Context, videoIDs []uint, model string, dim int) (map[uint][]float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadVectors", ctx, videoIDs, model, dim)
	ret0, _ := ret[0].(map[uint][]float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadVectors indicates an expected call of LoadVectors.
func (mr *MockVectorRecallStoreMockRecorder) LoadVectors(ctx, videoIDs, model, dim any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadVectors", reflect.TypeOf((*MockVectorRecallStore)(nil).LoadVectors), ctx, videoIDs, model, dim)
}

// RecentLikedVideoIDs mocks base method.
func (m *MockVectorRecallStore) RecentLikedVideoIDs(ctx context.Context, accountID uint, limit int) ([]uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecentLikedVideoIDs", ctx, accountID, limit)
	ret0, _ := ret[0].([]uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecentLikedVideoIDs indicates an expected call of RecentLikedVideoIDs.
func (mr *MockVectorRecallStoreMockRecorder) RecentLikedVideoIDs(ctx, accountID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecentLikedVideoIDs", reflect.TypeOf((*MockVectorRecallStore)(nil).RecentLikedVideoIDs), ctx, accountID, limit)
}
