// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/handlerzzy/feedsystem/internal/video (interfaces: CommentStore)
//
// Generated by this command:
//
//	mockgen -destination=mock/comment_store_mock.go -package=mock github.com/handlerzzy/feedsystem/internal/video CommentStore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	video "github.com/handlerzzy/feedsystem/internal/video"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCommentStore is a mock of CommentStore interface.
type MockCommentStore struct {
	ctrl     *gomock.Controller
	recorder *MockCommentStoreMockRecorder
	isgomock struct{}
}

// MockCommentStoreMockRecorder is the mock recorder for MockCommentStore.
type MockCommentStoreMockRecorder struct {
	mock *MockCommentStore
}

// NewMockCommentStore creates a new mock instance.
func NewMockCommentStore(ctrl *gomock.Controller) *MockCommentStore {
	mock := &MockCommentStore{ctrl: ctrl}
	mock.recorder = &MockCommentStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentStore) EXPECT() *MockCommentStoreMockRecorder {
	return m.recorder
}

// AccountIDByUsername mocks base method.
func (m *MockCommentStore) AccountIDByUsername(ctx context.Context, username string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountIDByUsername", ctx, username)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccountIDByUsername indicates an expected call of AccountIDByUsername.
func (mr *MockCommentStoreMockRecorder) AccountIDByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountIDByUsername", reflect.TypeOf((*MockCommentStore)(nil).AccountIDByUsername), ctx, username)
}

// CreateMentionNotification mocks base method.
func (m *MockCommentStore) CreateMentionNotification(ctx context.Context, n *video.MentionNotification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMentionNotification", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMentionNotification indicates an expected call of CreateMentionNotification.
func (mr *MockCommentStoreMockRecorder) CreateMentionNotification(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMentionNotification", reflect.TypeOf((*MockCommentStore)(nil).CreateMentionNotification), ctx, n)
}

// DeleteComment mocks base method.
func (m *MockCommentStore) DeleteComment(ctx context.Context, comment *video.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", ctx, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockCommentStoreMockRecorder) DeleteComment(ctx, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockCommentStore)(nil).DeleteComment), ctx, comment)
}

// GetAllComments mocks base method.
func (m *MockCommentStore) GetAllComments(ctx context.Context, videoID uint) ([]video.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllComments", ctx, videoID)
	ret0, _ := ret[0].([]video.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllComments indicates an expected call of GetAllComments.
func (mr *MockCommentStoreMockRecorder) GetAllComments(ctx, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllComments", reflect.TypeOf((*MockCommentStore)(nil).GetAllComments), ctx, videoID)
}

// GetByID mocks base method.
func (m *MockCommentStore) GetByID(ctx context.Context, id uint) (*video.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*video.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCommentStoreMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCommentStore)(nil).GetByID), ctx, id)
}

// PublishWithPopularity mocks base method.
func (m *MockCommentStore) PublishWithPopularity(ctx context.Context, comment *video.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishWithPopularity", ctx, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishWithPopularity indicates an expected call of PublishWithPopularity.
func (mr *MockCommentStoreMockRecorder) PublishWithPopularity(ctx, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishWithPopularity", reflect.TypeOf((*MockCommentStore)(nil).PublishWithPopularity), ctx, comment)
}
