// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/handlerzzy/feedsystem/internal/video (interfaces: CommentPublisher)
//
// Generated by this command:
//
//	mockgen -destination=mock/comment_publisher_mock.go -package=mock github.com/handlerzzy/feedsystem/internal/video CommentPublisher
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCommentPublisher is a mock of CommentPublisher interface.
type MockCommentPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockCommentPublisherMockRecorder
	isgomock struct{}
}

// MockCommentPublisherMockRecorder is the mock recorder for MockCommentPublisher.
type MockCommentPublisherMockRecorder struct {
	mock *MockCommentPublisher
}

// NewMockCommentPublisher creates a new mock instance.
func NewMockCommentPublisher(ctrl *gomock.Controller) *MockCommentPublisher {
	mock := &MockCommentPublisher{ctrl: ctrl}
	mock.recorder = &MockCommentPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentPublisher) EXPECT() *MockCommentPublisherMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCommentPublisher) Delete(ctx context.Context, commentID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, commentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCommentPublisherMockRecorder) Delete(ctx, commentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommentPublisher)(nil).Delete), ctx, commentID)
}

// Publish mocks base method.
func (m *MockCommentPublisher) Publish(ctx context.Context, username string, videoID, authorID uint, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, username, videoID, authorID, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockCommentPublisherMockRecorder) Publish(ctx, username, videoID, authorID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockCommentPublisher)(nil).Publish), ctx, username, videoID, authorID, content)
}
