// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/handlerzzy/feedsystem/internal/video (interfaces: ContentAnalysisPublisher)
//
// Generated by this command:
//
//	mockgen -destination=mock/content_analysis_publisher_mock.go -package=mock github.com/handlerzzy/feedsystem/internal/video ContentAnalysisPublisher
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	rabbitmq "github.com/handlerzzy/feedsystem/internal/middleware/rabbitmq"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockContentAnalysisPublisher is a mock of ContentAnalysisPublisher interface.
type MockContentAnalysisPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockContentAnalysisPublisherMockRecorder
	isgomock struct{}
}

// MockContentAnalysisPublisherMockRecorder is the mock recorder for MockContentAnalysisPublisher.
type MockContentAnalysisPublisherMockRecorder struct {
	mock *MockContentAnalysisPublisher
}

// NewMockContentAnalysisPublisher creates a new mock instance.
func NewMockContentAnalysisPublisher(ctrl *gomock.Controller) *MockContentAnalysisPublisher {
	mock := &MockContentAnalysisPublisher{ctrl: ctrl}
	mock.recorder = &MockContentAnalysisPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentAnalysisPublisher) EXPECT() *MockContentAnalysisPublisherMockRecorder {
	return m.recorder
}

// Request mocks base method.
func (m *MockContentAnalysisPublisher) Request(ctx context.Context, evt rabbitmq.ContentAnalysisEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", ctx, evt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Request indicates an expected call of Request.
func (mr *MockContentAnalysisPublisherMockRecorder) Request(ctx, evt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockContentAnalysisPublisher)(nil).Request), ctx, evt)
}
