// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/handlerzzy/feedsystem/internal/video (interfaces: LikeStore)
//
// Generated by this command:
//
//	mockgen -destination=mock/like_store_mock.go -package=mock github.com/handlerzzy/feedsystem/internal/video LikeStore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	video "github.com/handlerzzy/feedsystem/internal/video"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLikeStore is a mock of LikeStore interface.
type MockLikeStore struct {
	ctrl     *gomock.Controller
	recorder *MockLikeStoreMockRecorder
	isgomock struct{}
}

// MockLikeStoreMockRecorder is the mock recorder for MockLikeStore.
type MockLikeStoreMockRecorder struct {
	mock *MockLikeStore
}

// NewMockLikeStore creates a new mock instance.
func NewMockLikeStore(ctrl *gomock.Controller) *MockLikeStore {
	mock := &MockLikeStore{ctrl: ctrl}
	mock.recorder = &MockLikeStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikeStore) EXPECT() *MockLikeStoreMockRecorder {
	return m.recorder
}

// IsLiked mocks base method.
func (m *MockLikeStore) IsLiked(ctx context.Context, videoID, accountID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLiked", ctx, videoID, accountID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLiked indicates an expected call of IsLiked.
func (mr *MockLikeStoreMockRecorder) IsLiked(ctx, videoID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLiked", reflect.TypeOf((*MockLikeStore)(nil).IsLiked), ctx, videoID, accountID)
}

// LikeWithCounts mocks base method.
func (m *MockLikeStore) LikeWithCounts(ctx context.Context, like *video.Like) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LikeWithCounts", ctx, like)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LikeWithCounts indicates an expected call of LikeWithCounts.
func (mr *MockLikeStoreMockRecorder) LikeWithCounts(ctx, like any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LikeWithCounts", reflect.TypeOf((*MockLikeStore)(nil).LikeWithCounts), ctx, like)
}

// ListLikedVideos mocks base method.
func (m *MockLikeStore) ListLikedVideos(ctx context.Context, accountID uint) ([]video.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLikedVideos", ctx, accountID)
	ret0, _ := ret[0].([]video.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLikedVideos indicates an expected call of ListLikedVideos.
func (mr *MockLikeStoreMockRecorder) ListLikedVideos(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLikedVideos", reflect.TypeOf((*MockLikeStore)(nil).ListLikedVideos), ctx, accountID)
}

// UnlikeWithCounts mocks base method.
func (m *MockLikeStore) UnlikeWithCounts(ctx context.Context, videoID, accountID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlikeWithCounts", ctx, videoID, accountID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnlikeWithCounts indicates an expected call of UnlikeWithCounts.
func (mr *MockLikeStoreMockRecorder) UnlikeWithCounts(ctx, videoID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlikeWithCounts", reflect.TypeOf((*MockLikeStore)(nil).UnlikeWithCounts), ctx, videoID, accountID)
}
