// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/handlerzzy/feedsystem/internal/video (interfaces: LikePublisher)
//
// Generated by this command:
//
//	mockgen -destination=mock/like_publisher_mock.go -package=mock github.com/handlerzzy/feedsystem/internal/video LikePublisher
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLikePublisher is a mock of LikePublisher interface.
type MockLikePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockLikePublisherMockRecorder
	isgomock struct{}
}

// MockLikePublisherMockRecorder is the mock recorder for MockLikePublisher.
type MockLikePublisherMockRecorder struct {
	mock *MockLikePublisher
}

// NewMockLikePublisher creates a new mock instance.
func NewMockLikePublisher(ctrl *gomock.Controller) *MockLikePublisher {
	mock := &MockLikePublisher{ctrl: ctrl}
	mock.recorder = &MockLikePublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikePublisher) EXPECT() *MockLikePublisherMockRecorder {
	return m.recorder
}

// Like mocks base method.
func (m *MockLikePublisher) Like(ctx context.Context, userID, videoID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Like", ctx, userID, videoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Like indicates an expected call of Like.
func (mr *MockLikePublisherMockRecorder) Like(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Like", reflect.TypeOf((*MockLikePublisher)(nil).Like), ctx, userID, videoID)
}

// Unlike mocks base method.
func (m *MockLikePublisher) Unlike(ctx context.Context, userID, videoID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlike", ctx, userID, videoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unlike indicates an expected call of Unlike.
func (mr *MockLikePublisherMockRecorder) Unlike(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlike", reflect.TypeOf((*MockLikePublisher)(nil).Unlike), ctx, userID, videoID)
}
