// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/handlerzzy/feedsystem/internal/video (interfaces: PopularityPublisher)
//
// Generated by this command:
//
//	mockgen -destination=mock/popularity_publisher_mock.go -package=mock github.com/handlerzzy/feedsystem/internal/video PopularityPublisher
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPopularityPublisher is a mock of PopularityPublisher interface.
type MockPopularityPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPopularityPublisherMockRecorder
	isgomock struct{}
}

// MockPopularityPublisherMockRecorder is the mock recorder for MockPopularityPublisher.
type MockPopularityPublisherMockRecorder struct {
	mock *MockPopularityPublisher
}

// NewMockPopularityPublisher creates a new mock instance.
func NewMockPopularityPublisher(ctrl *gomock.Controller) *MockPopularityPublisher {
	mock := &MockPopularityPublisher{ctrl: ctrl}
	mock.recorder = &MockPopularityPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPopularityPublisher) EXPECT() *MockPopularityPublisherMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockPopularityPublisher) Update(ctx context.Context, videoID uint, change int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, videoID, change)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPopularityPublisherMockRecorder) Update(ctx, videoID, change any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPopularityPublisher)(nil).Update), ctx, videoID, change)
}
