// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/handlerzzy/feedsystem/internal/video (interfaces: VideoStore)
//
// Generated by this command:
//
//	mockgen -destination=mock/video_store_mock.go -package=mock github.com/handlerzzy/feedsystem/internal/video VideoStore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	video "github.com/handlerzzy/feedsystem/internal/video"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVideoStore is a mock of VideoStore interface.
type MockVideoStore struct {
	ctrl     *gomock.Controller
	recorder *MockVideoStoreMockRecorder
	isgomock struct{}
}

// MockVideoStoreMockRecorder is the mock recorder for MockVideoStore.
type MockVideoStoreMockRecorder struct {
	mock *MockVideoStore
}

// NewMockVideoStore creates a new mock instance.
func NewMockVideoStore(ctrl *gomock.Controller) *MockVideoStore {
	mock := &MockVideoStore{ctrl: ctrl}
	mock.recorder = &MockVideoStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoStore) EXPECT() *MockVideoStoreMockRecorder {
	return m.recorder
}

// DeleteVideo mocks base method.
func (m *MockVideoStore) DeleteVideo(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVideo", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVideo indicates an expected call of DeleteVideo.
func (mr *MockVideoStoreMockRecorder) DeleteVideo(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVideo", reflect.TypeOf((*MockVideoStore)(nil).DeleteVideo), ctx, id)
}

// GetByID mocks base method.
func (m *MockVideoStore) GetByID(ctx context.Context, id uint) (*video.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*video.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockVideoStoreMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockVideoStore)(nil).GetByID), ctx, id)
}

// ListByAuthorID mocks base method.
func (m *MockVideoStore) ListByAuthorID(ctx context.Context, authorID int64) ([]video.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAuthorID", ctx, authorID)
	ret0, _ := ret[0].([]video.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAuthorID indicates an expected call of ListByAuthorID.
func (mr *MockVideoStoreMockRecorder) ListByAuthorID(ctx, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAuthorID", reflect.TypeOf((*MockVideoStore)(nil).ListByAuthorID), ctx, authorID)
}

// PublishWithOutbox mocks base method.
func (m *MockVideoStore) PublishWithOutbox(ctx context.Context, arg1 *video.Video) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishWithOutbox", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishWithOutbox indicates an expected call of PublishWithOutbox.
func (mr *MockVideoStoreMockRecorder) PublishWithOutbox(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishWithOutbox", reflect.TypeOf((*MockVideoStore)(nil).PublishWithOutbox), ctx, arg1)
}
