// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/handlerzzy/feedsystem/internal/video (interfaces: VideoExistenceStore)
//
// Generated by this command:
//
//	mockgen -destination=mock/video_existence_store_mock.go -package=mock github.com/handlerzzy/feedsystem/internal/video VideoExistenceStore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVideoExistenceStore is a mock of VideoExistenceStore interface.
type MockVideoExistenceStore struct {
	ctrl     *gomock.Controller
	recorder *MockVideoExistenceStoreMockRecorder
	isgomock struct{}
}

// MockVideoExistenceStoreMockRecorder is the mock recorder for MockVideoExistenceStore.
type MockVideoExistenceStoreMockRecorder struct {
	mock *MockVideoExistenceStore
}

// NewMockVideoExistenceStore creates a new mock instance.
func NewMockVideoExistenceStore(ctrl *gomock.Controller) *MockVideoExistenceStore {
	mock := &MockVideoExistenceStore{ctrl: ctrl}
	mock.recorder = &MockVideoExistenceStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoExistenceStore) EXPECT() *MockVideoExistenceStoreMockRecorder {
	return m.recorder
}

// IsExist mocks base method.
func (m *MockVideoExistenceStore) IsExist(ctx context.Context, id uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExist", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsExist indicates an expected call of IsExist.
func (mr *MockVideoExistenceStoreMockRecorder) IsExist(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExist", reflect.TypeOf((*MockVideoExistenceStore)(nil).IsExist), ctx, id)
}
