// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/handlerzzy/feedsystem/internal/middleware/jwt (interfaces: AccountLookup)
//
// Generated by this command:
//
//	mockgen -destination=mock/account_lookup_mock.go -package=mock github.com/handlerzzy/feedsystem/internal/middleware/jwt AccountLookup
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	account "github.com/handlerzzy/feedsystem/internal/account"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAccountLookup is a mock of AccountLookup interface.
type MockAccountLookup struct {
	ctrl     *gomock.Controller
	recorder *MockAccountLookupMockRecorder
	isgomock struct{}
}

// MockAccountLookupMockRecorder is the mock recorder for MockAccountLookup.
type MockAccountLookupMockRecorder struct {
	mock *MockAccountLookup
}

// NewMockAccountLookup creates a new mock instance.
func NewMockAccountLookup(ctrl *gomock.Controller) *MockAccountLookup {
	mock := &MockAccountLookup{ctrl: ctrl}
	mock.recorder = &MockAccountLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountLookup) EXPECT() *MockAccountLookupMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockAccountLookup) FindByID(ctx context.Context, id uint) (*account.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAccountLookupMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAccountLookup)(nil).FindByID), ctx, id)
}
