// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/handlerzzy/feedsystem/internal/account (interfaces: AccountStore)
//
// Generated by this command:
//
//	mockgen -destination=mock/account_store_mock.go -package=mock github.com/handlerzzy/feedsystem/internal/account AccountStore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	account "github.com/handlerzzy/feedsystem/internal/account"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAccountStore is a mock of AccountStore interface.
type MockAccountStore struct {
	ctrl     *gomock.Controller
	recorder *MockAccountStoreMockRecorder
	isgomock struct{}
}

// MockAccountStoreMockRecorder is the mock recorder for MockAccountStore.
type MockAccountStoreMockRecorder struct {
	mock *MockAccountStore
}

// NewMockAccountStore creates a new mock instance.
func NewMockAccountStore(ctrl *gomock.Controller) *MockAccountStore {
	mock := &MockAccountStore{ctrl: ctrl}
	mock.recorder = &MockAccountStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountStore) EXPECT() *MockAccountStoreMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockAccountStore) ChangePassword(ctx context.Context, id uint, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, id, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockAccountStoreMockRecorder) ChangePassword(ctx, id, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockAccountStore)(nil).ChangePassword), ctx, id, newPassword)
}

// CreateAccount mocks base method.
func (m *MockAccountStore) CreateAccount(ctx context.Context, arg1 *account.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockAccountStoreMockRecorder) CreateAccount(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockAccountStore)(nil).CreateAccount), ctx, arg1)
}

// FindByID mocks base method.
func (m *MockAccountStore) FindByID(ctx context.Context, id uint) (*account.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAccountStoreMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAccountStore)(nil).FindByID), ctx, id)
}

// FindByUsername mocks base method.
func (m *MockAccountStore) FindByUsername(ctx context.Context, username string) (*account.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUsername", ctx, username)
	ret0, _ := ret[0].(*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUsername indicates an expected call of FindByUsername.
func (mr *MockAccountStoreMockRecorder) FindByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUsername", reflect.TypeOf((*MockAccountStore)(nil).FindByUsername), ctx, username)
}

// Login mocks base method.
func (m *MockAccountStore) Login(ctx context.Context, id uint, token, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, id, token, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockAccountStoreMockRecorder) Login(ctx, id, token, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAccountStore)(nil).Login), ctx, id, token, refreshToken)
}

// Logout mocks base method.
func (m *MockAccountStore) Logout(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAccountStoreMockRecorder) Logout(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAccountStore)(nil).Logout), ctx, id)
}

// RenameWithToken mocks base method.
func (m *MockAccountStore) RenameWithToken(ctx context.Context, id uint, newUsername, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenameWithToken", ctx, id, newUsername, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenameWithToken indicates an expected call of RenameWithToken.
func (mr *MockAccountStoreMockRecorder) RenameWithToken(ctx, id, newUsername, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameWithToken", reflect.TypeOf((*MockAccountStore)(nil).RenameWithToken), ctx, id, newUsername, token)
}

// UpdateAvatar mocks base method.
func (m *MockAccountStore) UpdateAvatar(ctx context.Context, accountID uint, avatarURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatar", ctx, accountID, avatarURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvatar indicates an expected call of UpdateAvatar.
func (mr *MockAccountStoreMockRecorder) UpdateAvatar(ctx, accountID, avatarURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatar", reflect.TypeOf((*MockAccountStore)(nil).UpdateAvatar), ctx, accountID, avatarURL)
}

// UpdateFields mocks base method.
func (m *MockAccountStore) UpdateFields(ctx context.Context, id uint, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFields", ctx, id, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFields indicates an expected call of UpdateFields.
func (mr *MockAccountStoreMockRecorder) UpdateFields(ctx, id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFields", reflect.TypeOf((*MockAccountStore)(nil).UpdateFields), ctx, id, updates)
}

// UpdateToken mocks base method.
func (m *MockAccountStore) UpdateToken(ctx context.Context, id uint, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateToken", ctx, id, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateToken indicates an expected call of UpdateToken.
func (mr *MockAccountStoreMockRecorder) UpdateToken(ctx, id, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateToken", reflect.TypeOf((*MockAccountStore)(nil).UpdateToken), ctx, id, token)
}
