// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/handlerzzy/feedsystem/internal/social (interfaces: SocialStore)
//
// Generated by this command:
//
//	mockgen -destination=mock/social_store_mock.go -package=mock github.com/handlerzzy/feedsystem/internal/social SocialStore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	account "github.com/handlerzzy/feedsystem/internal/account"
	social "github.com/handlerzzy/feedsystem/internal/social"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSocialStore is a mock of SocialStore interface.
type MockSocialStore struct {
	ctrl     *gomock.Controller
	recorder *MockSocialStoreMockRecorder
	isgomock struct{}
}

// MockSocialStoreMockRecorder is the mock recorder for MockSocialStore.
type MockSocialStoreMockRecorder struct {
	mock *MockSocialStore
}

// NewMockSocialStore creates a new mock instance.
func NewMockSocialStore(ctrl *gomock.Controller) *MockSocialStore {
	mock := &MockSocialStore{ctrl: ctrl}
	mock.recorder = &MockSocialStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSocialStore) EXPECT() *MockSocialStoreMockRecorder {
	return m.recorder
}

// CountFollowers mocks base method.
func (m *MockSocialStore) CountFollowers(ctx context.Context, vloggerID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFollowers", ctx, vloggerID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFollowers indicates an expected call of CountFollowers.
func (mr *MockSocialStoreMockRecorder) CountFollowers(ctx, vloggerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFollowers", reflect.TypeOf((*MockSocialStore)(nil).CountFollowers), ctx, vloggerID)
}

// CountVloggers mocks base method.
func (m *MockSocialStore) CountVloggers(ctx context.Context, followerID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountVloggers", ctx, followerID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountVloggers indicates an expected call of CountVloggers.
func (mr *MockSocialStoreMockRecorder) CountVloggers(ctx, followerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountVloggers", reflect.TypeOf((*MockSocialStore)(nil).CountVloggers), ctx, followerID)
}

// Follow mocks base method.
func (m *MockSocialStore) Follow(ctx context.Context, arg1 *social.Social) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Follow", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Follow indicates an expected call of Follow.
func (mr *MockSocialStoreMockRecorder) Follow(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockSocialStore)(nil).Follow), ctx, arg1)
}

// GetAllFollowers mocks base method.
func (m *MockSocialStore) GetAllFollowers(ctx context.Context, VloggerID uint) ([]*account.PublicAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllFollowers", ctx, VloggerID)
	ret0, _ := ret[0].([]*account.PublicAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllFollowers indicates an expected call of GetAllFollowers.
func (mr *MockSocialStoreMockRecorder) GetAllFollowers(ctx, VloggerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllFollowers", reflect.TypeOf((*MockSocialStore)(nil).GetAllFollowers), ctx, VloggerID)
}

// GetAllVloggers mocks base method.
func (m *MockSocialStore) GetAllVloggers(ctx context.Context, FollowerID uint) ([]*account.PublicAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllVloggers", ctx, FollowerID)
	ret0, _ := ret[0].([]*account.PublicAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllVloggers indicates an expected call of GetAllVloggers.
func (mr *MockSocialStoreMockRecorder) GetAllVloggers(ctx, FollowerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllVloggers", reflect.TypeOf((*MockSocialStore)(nil).GetAllVloggers), ctx, FollowerID)
}

// IsFollowed mocks base method.
func (m *MockSocialStore) IsFollowed(ctx context.Context, arg1 *social.Social) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFollowed", ctx, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFollowed indicates an expected call of IsFollowed.
func (mr *MockSocialStoreMockRecorder) IsFollowed(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFollowed", reflect.TypeOf((*MockSocialStore)(nil).IsFollowed), ctx, arg1)
}

// Unfollow mocks base method.
func (m *MockSocialStore) Unfollow(ctx context.Context, arg1 *social.Social) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unfollow", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unfollow indicates an expected call of Unfollow.
func (mr *MockSocialStoreMockRecorder) Unfollow(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unfollow", reflect.TypeOf((*MockSocialStore)(nil).Unfollow), ctx, arg1)
}
