// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/handlerzzy/feedsystem/internal/social (interfaces: SocialPublisher)
//
// Generated by this command:
//
//	mockgen -destination=mock/social_publisher_mock.go -package=mock github.com/handlerzzy/feedsystem/internal/social SocialPublisher
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSocialPublisher is a mock of SocialPublisher interface.
type MockSocialPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockSocialPublisherMockRecorder
	isgomock struct{}
}

// MockSocialPublisherMockRecorder is the mock recorder for MockSocialPublisher.
type MockSocialPublisherMockRecorder struct {
	mock *MockSocialPublisher
}

// NewMockSocialPublisher creates a new mock instance.
func NewMockSocialPublisher(ctrl *gomock.Controller) *MockSocialPublisher {
	mock := &MockSocialPublisher{ctrl: ctrl}
	mock.recorder = &MockSocialPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSocialPublisher) EXPECT() *MockSocialPublisherMockRecorder {
	return m.recorder
}

// Follow mocks base method.
func (m *MockSocialPublisher) Follow(ctx context.Context, followerID, vloggerID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Follow", ctx, followerID, vloggerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Follow indicates an expected call of Follow.
func (mr *MockSocialPublisherMockRecorder) Follow(ctx, followerID, vloggerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockSocialPublisher)(nil).Follow), ctx, followerID, vloggerID)
}

// UnFollow mocks base method.
func (m *MockSocialPublisher) UnFollow(ctx context.Context, followerID, vloggerID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnFollow", ctx, followerID, vloggerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnFollow indicates an expected call of UnFollow.
func (mr *MockSocialPublisherMockRecorder) UnFollow(ctx, followerID, vloggerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnFollow", reflect.TypeOf((*MockSocialPublisher)(nil).UnFollow), ctx, followerID, vloggerID)
}
