// ModelGateway —— Go 侧（client）与 Node sidecar（server）之间的唯一契约。
//
// 为什么单独抽一个 sidecar 而不是在 Go 里直接调模型 SDK：
// 模型生态（多 provider、流式、token/成本计量、重试与限流）迭代速度远快于
// 本项目的发布节奏，把它关在一个可独立部署、可独立回退、**可以整个删掉**的
// 进程里，AI 才符合"锦上添花，不是承重墙"的定位。Go 侧只依赖下面这三个方法，
// 换 provider / 换 SDK 不需要动业务代码，也不需要重新编译后端。
//
// 契约纪律（与 docs/AI-00-总览与全局约束.md 第 2 节红线同精神）：
//   字段只增不删、不改语义、不重用已删除的 tag 号；新增字段必须可缺省。
//   原因：Go 侧与 sidecar 是两个独立部署的进程，滚动升级期间新旧版本必然共存。
//   删字段或改 tag 会让"老客户端 + 新服务端"在运行期直接解析错乱，
//   而这类错在单测里永远发现不了。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: ai/v1/model_gateway.proto

package aiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelGateway_Complete_FullMethodName       = "/ai.v1.ModelGateway/Complete"
	ModelGateway_CompleteStream_FullMethodName = "/ai.v1.ModelGateway/CompleteStream"
	ModelGateway_Health_FullMethodName         = "/ai.v1.ModelGateway/Health"
	ModelGateway_Embed_FullMethodName          = "/ai.v1.ModelGateway/Embed"
)

// ModelGatewayClient is the client API for ModelGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ModelGateway 是模型能力的唯一入口。它刻意不知道任何业务概念
// （没有"视频""标签""审核"这些词）：业务语义留在 Go 侧，sidecar 只做
// "文本进、结构化结果出"的通用转换。这样 P1 打标、P3 审核、P4 Agent
// 可以共用同一个 sidecar，而每次新增业务场景都不需要改协议。
type ModelGatewayClient interface {
	// Complete 非流式补全，支持结构化（JSON）输出。P1/P3 走这个方法。
	Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error)
	// CompleteStream 流式补全。P0 只定义契约、不接业务，为 P4 运营 Agent 预留：
	// Agent 的中间步骤需要边生成边展示，非流式接口无法承载。
	CompleteStream(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CompleteChunk], error)
	// Health 健康检查与自描述。Go 侧用它判断"sidecar 在不在、能不能用"，
	// 不使用 gRPC 标准 health 协议是为了让 sidecar 能顺便汇报自己配置了哪些
	// provider、总开关是否打开——这决定了 Go 侧该走真实调用还是直接降级。
	//
	// serving=false 时调用方**应当**（SHOULD，不是 MUST）跳过 Complete 直接降级：
	// 让一次注定失败的调用白吃一个超时预算是浪费。之所以不写成 MUST——
	// 要求每个调用点缓存健康状态会引入"缓存过期"这一类新问题，
	// 而多花的那一次往返在 2 秒预算里是可以接受的代价。
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Embed 批量生成文本向量。P2 的语义召回用它。
	//
	// 为什么单独一个方法而不是塞进 Complete：
	//   - 语义完全不同。chat 是"生成"，embedding 是"编码"：没有 temperature、
	//     没有 max_tokens、没有流式，但必须支持批量与维度声明；
	//   - 传输链路也不同。本项目的 chat 走 pi-ai（只收录支持 function calling
	//     的模型，**不含 embedding**），embedding 必须单独接一条
	//     OpenAI 兼容的 /v1/embeddings 路径。硬塞进 Complete 只能靠在
	//     prompt 里要一段 JSON 数字数组，那是必然出错的捷径；
	//   - 配额与超时语义不同。混在一起之后，一次 embedding 超时会去影响
	//     chat 的重试与熔断判断。
	//
	// 定死的取值（换模型必须同时改这里、Go 侧配置与向量表的 model/dim 记录）：
	//
	//	默认模型   text-embedding-3-small
	//	默认维度   1536
	//	默认归一化 true（L2）
	//
	// 这三条必须写进配置或注释，否则将来换模型要全量重算且无据可查。
	Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error)
}

type modelGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewModelGatewayClient(cc grpc.ClientConnInterface) ModelGatewayClient {
	return &modelGatewayClient{cc}
}

func (c *modelGatewayClient) Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteResponse)
	err := c.cc.Invoke(ctx, ModelGateway_Complete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelGatewayClient) CompleteStream(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CompleteChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ModelGateway_ServiceDesc.Streams[0], ModelGateway_CompleteStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CompleteRequest, CompleteChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelGateway_CompleteStreamClient = grpc.ServerStreamingClient[CompleteChunk]

func (c *modelGatewayClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ModelGateway_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelGatewayClient) Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedResponse)
	err := c.cc.Invoke(ctx, ModelGateway_Embed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelGatewayServer is the server API for ModelGateway service.
// All implementations should embed UnimplementedModelGatewayServer
// for forward compatibility.
//
// ModelGateway 是模型能力的唯一入口。它刻意不知道任何业务概念
// （没有"视频""标签""审核"这些词）：业务语义留在 Go 侧，sidecar 只做
// "文本进、结构化结果出"的通用转换。这样 P1 打标、P3 审核、P4 Agent
// 可以共用同一个 sidecar，而每次新增业务场景都不需要改协议。
type ModelGatewayServer interface {
	// Complete 非流式补全，支持结构化（JSON）输出。P1/P3 走这个方法。
	Complete(context.Context, *CompleteRequest) (*CompleteResponse, error)
	// CompleteStream 流式补全。P0 只定义契约、不接业务，为 P4 运营 Agent 预留：
	// Agent 的中间步骤需要边生成边展示，非流式接口无法承载。
	CompleteStream(*CompleteRequest, grpc.ServerStreamingServer[CompleteChunk]) error
	// Health 健康检查与自描述。Go 侧用它判断"sidecar 在不在、能不能用"，
	// 不使用 gRPC 标准 health 协议是为了让 sidecar 能顺便汇报自己配置了哪些
	// provider、总开关是否打开——这决定了 Go 侧该走真实调用还是直接降级。
	//
	// serving=false 时调用方**应当**（SHOULD，不是 MUST）跳过 Complete 直接降级：
	// 让一次注定失败的调用白吃一个超时预算是浪费。之所以不写成 MUST——
	// 要求每个调用点缓存健康状态会引入"缓存过期"这一类新问题，
	// 而多花的那一次往返在 2 秒预算里是可以接受的代价。
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Embed 批量生成文本向量。P2 的语义召回用它。
	//
	// 为什么单独一个方法而不是塞进 Complete：
	//   - 语义完全不同。chat 是"生成"，embedding 是"编码"：没有 temperature、
	//     没有 max_tokens、没有流式，但必须支持批量与维度声明；
	//   - 传输链路也不同。本项目的 chat 走 pi-ai（只收录支持 function calling
	//     的模型，**不含 embedding**），embedding 必须单独接一条
	//     OpenAI 兼容的 /v1/embeddings 路径。硬塞进 Complete 只能靠在
	//     prompt 里要一段 JSON 数字数组，那是必然出错的捷径；
	//   - 配额与超时语义不同。混在一起之后，一次 embedding 超时会去影响
	//     chat 的重试与熔断判断。
	//
	// 定死的取值（换模型必须同时改这里、Go 侧配置与向量表的 model/dim 记录）：
	//
	//	默认模型   text-embedding-3-small
	//	默认维度   1536
	//	默认归一化 true（L2）
	//
	// 这三条必须写进配置或注释，否则将来换模型要全量重算且无据可查。
	Embed(context.Context, *EmbedRequest) (*EmbedResponse, error)
}

// UnimplementedModelGatewayServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelGatewayServer struct{}

func (UnimplementedModelGatewayServer) Complete(context.Context, *CompleteRequest) (*CompleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedModelGatewayServer) CompleteStream(*CompleteRequest, grpc.ServerStreamingServer[CompleteChunk]) error {
	return status.Errorf(codes.Unimplemented, "method CompleteStream not implemented")
}
func (UnimplementedModelGatewayServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedModelGatewayServer) Embed(context.Context, *EmbedRequest) (*EmbedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Embed not implemented")
}
func (UnimplementedModelGatewayServer) testEmbeddedByValue() {}

// UnsafeModelGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelGatewayServer will
// result in compilation errors.
type UnsafeModelGatewayServer interface {
	mustEmbedUnimplementedModelGatewayServer()
}

func RegisterModelGatewayServer(s grpc.ServiceRegistrar, srv ModelGatewayServer) {
	// If the following call pancis, it indicates UnimplementedModelGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelGateway_ServiceDesc, srv)
}

func _ModelGateway_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelGatewayServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelGateway_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelGatewayServer).Complete(ctx, req.(*CompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelGateway_CompleteStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CompleteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModelGatewayServer).CompleteStream(m, &grpc.GenericServerStream[CompleteRequest, CompleteChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelGateway_CompleteStreamServer = grpc.ServerStreamingServer[CompleteChunk]

func _ModelGateway_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelGatewayServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelGateway_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelGatewayServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelGateway_Embed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelGatewayServer).Embed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelGateway_Embed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelGatewayServer).Embed(ctx, req.(*EmbedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelGateway_ServiceDesc is the grpc.ServiceDesc for ModelGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.v1.ModelGateway",
	HandlerType: (*ModelGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Complete",
			Handler:    _ModelGateway_Complete_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ModelGateway_Health_Handler,
		},
		{
			MethodName: "Embed",
			Handler:    _ModelGateway_Embed_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CompleteStream",
			Handler:       _ModelGateway_CompleteStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai/v1/model_gateway.proto",
}
