// ModelGateway —— Go 侧（client）与 Node sidecar（server）之间的唯一契约。
//
// 为什么单独抽一个 sidecar 而不是在 Go 里直接调模型 SDK：
// 模型生态（多 provider、流式、token/成本计量、重试与限流）迭代速度远快于
// 本项目的发布节奏，把它关在一个可独立部署、可独立回退、**可以整个删掉**的
// 进程里，AI 才符合"锦上添花，不是承重墙"的定位。Go 侧只依赖下面这三个方法，
// 换 provider / 换 SDK 不需要动业务代码，也不需要重新编译后端。
//
// 契约纪律（与 docs/AI-00-总览与全局约束.md 第 2 节红线同精神）：
//   字段只增不删、不改语义、不重用已删除的 tag 号；新增字段必须可缺省。
//   原因：Go 侧与 sidecar 是两个独立部署的进程，滚动升级期间新旧版本必然共存。
//   删字段或改 tag 会让"老客户端 + 新服务端"在运行期直接解析错乱，
//   而这类错在单测里永远发现不了。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: ai/v1/model_gateway.proto

package aiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// model 留空时由 sidecar 按自身配置选默认模型。允许留空是刻意的：
	// 换模型只改 sidecar 配置，不必让所有调用方跟着发版。
	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	// system / prompt 分开而不是拼成一条字符串：provider 的 system 角色
	// 与用户消息在多数 SDK 里是不同参数，合并后无法再拆开。
	System string `protobuf:"bytes,2,opt,name=system,proto3" json:"system,omitempty"`
	Prompt string `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// temperature / max_tokens 为 0 表示"用 sidecar 的默认值"。
	// 不设 proto3 的 optional 是为了让 Go 侧零值语义简单：0 即未指定。
	Temperature float64 `protobuf:"fixed64,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens   int32   `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	// response_format = "json" 时，sidecar 必须保证返回体是合法 JSON 对象；
	// 无法保证时应返回错误，而不是把半截 JSON 当成功结果交回来
	// （调用方据此入库，脏数据比失败更难查——见总览第 4 节）。
	ResponseFormat string `protobuf:"bytes,6,opt,name=response_format,json=responseFormat,proto3" json:"response_format,omitempty"`
	// request_id 由 Go 侧生成，用于把一次业务请求在 Go 日志与 sidecar 日志
	// 之间对起来。不含任何用户身份信息，避免把 PII 带出进程边界。
	RequestId     string `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_ai_v1_model_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_model_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_model_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *CompleteRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompleteRequest) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *CompleteRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CompleteRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *CompleteRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *CompleteRequest) GetResponseFormat() string {
	if x != nil {
		return x.ResponseFormat
	}
	return ""
}

func (x *CompleteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CompleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// text 是模型输出的原始文本。结构化输出时调用方仍需自己校验 JSON：
	// 协议层不替业务做 schema 校验，否则每个新场景都要改 proto。
	Text  string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// usage 用于成本核算。字段缺失（老 sidecar）时按 0 记账，不得因此报错。
	Usage         *Usage `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_ai_v1_model_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_model_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_model_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *CompleteResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CompleteResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompleteResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type CompleteChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// delta 是本片新增文本（不是累计全文），拼接语义由调用方决定。
	Delta string `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	// done 为 true 的那一片之后不会再有数据；usage 只在最后一片上有值。
	Done          bool   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	Usage         *Usage `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteChunk) Reset() {
	*x = CompleteChunk{}
	mi := &file_ai_v1_model_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteChunk) ProtoMessage() {}

func (x *CompleteChunk) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_model_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteChunk.ProtoReflect.Descriptor instead.
func (*CompleteChunk) Descriptor() ([]byte, []int) {
	return file_ai_v1_model_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteChunk) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *CompleteChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *CompleteChunk) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type Usage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	// cost_usd 由 sidecar 按自己的价目表算出，Go 侧只做记录与上报。
	CostUsd       float64 `protobuf:"fixed64,4,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_ai_v1_model_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_model_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_ai_v1_model_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *Usage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *Usage) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

type EmbedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// inputs 是待向量化的文本列表，最多 64 条（见 sidecar 的校验）。
	//
	// 为什么是批量而不是单条：批量是 embedding 唯一能把吞吐做上去的方式。
	// 回填历史视频时逐条调用会把延迟乘以条数，也会让"一次请求一次计费"
	// 的账变得难以核对。上限 64 是"单请求体不要撑爆 gRPC 消息限制"的折中。
	Inputs []string `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// model 留空时由 sidecar 按自身配置选默认 embedding 模型。
	// 与 CompleteRequest.model 同样的理由：换模型只改 sidecar 配置。
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// normalize=true 时 sidecar 必须返回 **L2 归一化** 后的向量。
	//
	// 为什么把这件事放进协议而不是"由调用方自己归一化"：
	// 归一化与否决定了余弦相似度能不能退化成点积，一旦两边理解不一致，
	// 检索结果会静默变差（分数仍然"看起来正常"）。写进协议之后，
	// 响应里的 normalized 字段还能回显实际行为，不一致立刻可查。
	Normalize bool `protobuf:"varint,3,opt,name=normalize,proto3" json:"normalize,omitempty"`
	// request_id 由 Go 侧生成，用于把一次业务请求在 Go 日志与 sidecar 日志
	// 之间对起来（与 CompleteRequest.request_id 同义）。
	RequestId     string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_ai_v1_model_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_model_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_model_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *EmbedRequest) GetInputs() []string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *EmbedRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbedRequest) GetNormalize() bool {
	if x != nil {
		return x.Normalize
	}
	return false
}

func (x *EmbedRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type Embedding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// values 是这一条文本的向量。**不要求**定长校验由协议层做：
	// 调用方必须自己检查 len(values) == EmbedResponse.dim，
	// 因为"某一行的维度不对"是真实会发生的（provider 截断、解析错位），
	// 而带着错误维度入库的向量在检索时才暴露，且看起来像"模型效果差"。
	Values        []float32 `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	mi := &file_ai_v1_model_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_model_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_ai_v1_model_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *Embedding) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type EmbedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// vectors 与请求的 inputs **一一对应且顺序一致**。
	// 数量不匹配时调用方必须整批判为失败，不能"按能对上的部分入库"——
	// 那会把文本与向量错配，而这种错误在检索结果里完全看不出来。
	Vectors []*Embedding `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"`
	Model   string       `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// dim 是所有向量的维度。换模型/换维度时它一定会变，
	// 调用方据此判断已入库的向量是否失效（必须重算）。
	Dim int32 `protobuf:"varint,3,opt,name=dim,proto3" json:"dim,omitempty"`
	// normalized 回显 sidecar 实际做的处理（不是回显请求）。
	// 请求 true 而响应 false 说明对端实现有分歧，调用方可以据此拒绝入库。
	Normalized bool `protobuf:"varint,4,opt,name=normalized,proto3" json:"normalized,omitempty"`
	// usage 复用 Usage：embedding 的输入量填在 prompt_tokens/total_tokens，
	// completion_tokens 恒为 0。复用而不是新开一个消息，是为了让
	// "成本核算"在所有模型调用上只有一套口径。
	Usage         *Usage `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_ai_v1_model_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_model_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_model_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *EmbedResponse) GetVectors() []*Embedding {
	if x != nil {
		return x.Vectors
	}
	return nil
}

func (x *EmbedResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbedResponse) GetDim() int32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *EmbedResponse) GetNormalized() bool {
	if x != nil {
		return x.Normalized
	}
	return false
}

func (x *EmbedResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_ai_v1_model_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_model_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_model_gateway_proto_rawDescGZIP(), []int{7}
}

type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// serving = false 表示 sidecar 活着但**不提供模型服务**（总开关关闭或
	// 一个 provider key 都没配）。此时 Go 侧必须直接降级，不要去调 Complete：
	// 让它失败再降级会白白吃掉一次超时预算。
	Serving bool   `protobuf:"varint,1,opt,name=serving,proto3" json:"serving,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// providers 是已配置 key 的 provider 名，仅用于诊断展示；不得包含 key 本身。
	Providers []string `protobuf:"bytes,3,rep,name=providers,proto3" json:"providers,omitempty"`
	// detail 是给人看的诊断信息。**禁止**写入任何密钥或密钥片段。
	Detail        string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_ai_v1_model_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_model_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_model_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetServing() bool {
	if x != nil {
		return x.Serving
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *HealthResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_ai_v1_model_gateway_proto protoreflect.FileDescriptor

const file_ai_v1_model_gateway_proto_rawDesc = "" +
	"\n" +
	"\x19ai/v1/model_gateway.proto\x12\x05ai.v1\"\xe0\x01\n" +
	"\x0fCompleteRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x16\n" +
	"\x06system\x18\x02 \x01(\tR\x06system\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x01R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\x12'\n" +
	"\x0fresponse_format\x18\x06 \x01(\tR\x0eresponseFormat\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\"`\n" +
	"\x10CompleteResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\"\n" +
	"\x05usage\x18\x03 \x01(\v2\f.ai.v1.UsageR\x05usage\"]\n" +
	"\rCompleteChunk\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\"\n" +
	"\x05usage\x18\x03 \x01(\v2\f.ai.v1.UsageR\x05usage\"\x97\x01\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\x12\x19\n" +
	"\bcost_usd\x18\x04 \x01(\x01R\acostUsd\"y\n" +
	"\fEmbedRequest\x12\x16\n" +
	"\x06inputs\x18\x01 \x03(\tR\x06inputs\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1c\n" +
	"\tnormalize\x18\x03 \x01(\bR\tnormalize\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"#\n" +
	"\tEmbedding\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"\xa7\x01\n" +
	"\rEmbedResponse\x12*\n" +
	"\avectors\x18\x01 \x03(\v2\x10.ai.v1.EmbeddingR\avectors\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x10\n" +
	"\x03dim\x18\x03 \x01(\x05R\x03dim\x12\x1e\n" +
	"\n" +
	"normalized\x18\x04 \x01(\bR\n" +
	"normalized\x12\"\n" +
	"\x05usage\x18\x05 \x01(\v2\f.ai.v1.UsageR\x05usage\"\x0f\n" +
	"\rHealthRequest\"z\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\aserving\x18\x01 \x01(\bR\aserving\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tproviders\x18\x03 \x03(\tR\tproviders\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail2\xf8\x01\n" +
	"\fModelGateway\x12;\n" +
	"\bComplete\x12\x16.ai.v1.CompleteRequest\x1a\x17.ai.v1.CompleteResponse\x12@\n" +
	"\x0eCompleteStream\x12\x16.ai.v1.CompleteRequest\x1a\x14.ai.v1.CompleteChunk0\x01\x125\n" +
	"\x06Health\x12\x14.ai.v1.HealthRequest\x1a\x15.ai.v1.HealthResponse\x122\n" +
	"\x05Embed\x12\x13.ai.v1.EmbedRequest\x1a\x14.ai.v1.EmbedResponseB\x8e\x01\n" +
	"\tcom.ai.v1B\x11ModelGatewayProtoP\x01Z9github.com/handlerzzy/feedsystem/internal/aipb/ai/v1;aiv1\xa2\x02\x03AXX\xaa\x02\x05Ai.V1\xca\x02\x05Ai\\V1\xe2\x02\x11Ai\\V1\\GPBMetadata\xea\x02\x06Ai::V1b\x06proto3"

var (
	file_ai_v1_model_gateway_proto_rawDescOnce sync.Once
	file_ai_v1_model_gateway_proto_rawDescData []byte
)

func file_ai_v1_model_gateway_proto_rawDescGZIP() []byte {
	file_ai_v1_model_gateway_proto_rawDescOnce.Do(func() {
		file_ai_v1_model_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_v1_model_gateway_proto_rawDesc), len(file_ai_v1_model_gateway_proto_rawDesc)))
	})
	return file_ai_v1_model_gateway_proto_rawDescData
}

var file_ai_v1_model_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ai_v1_model_gateway_proto_goTypes = []any{
	(*CompleteRequest)(nil),  // 0: ai.v1.CompleteRequest
	(*CompleteResponse)(nil), // 1: ai.v1.CompleteResponse
	(*CompleteChunk)(nil),    // 2: ai.v1.CompleteChunk
	(*Usage)(nil),            // 3: ai.v1.Usage
	(*EmbedRequest)(nil),     // 4: ai.v1.EmbedRequest
	(*Embedding)(nil),        // 5: ai.v1.Embedding
	(*EmbedResponse)(nil),    // 6: ai.v1.EmbedResponse
	(*HealthRequest)(nil),    // 7: ai.v1.HealthRequest
	(*HealthResponse)(nil),   // 8: ai.v1.HealthResponse
}
var file_ai_v1_model_gateway_proto_depIdxs = []int32{
	3, // 0: ai.v1.CompleteResponse.usage:type_name -> ai.v1.Usage
	3, // 1: ai.v1.CompleteChunk.usage:type_name -> ai.v1.Usage
	5, // 2: ai.v1.EmbedResponse.vectors:type_name -> ai.v1.Embedding
	3, // 3: ai.v1.EmbedResponse.usage:type_name -> ai.v1.Usage
	0, // 4: ai.v1.ModelGateway.Complete:input_type -> ai.v1.CompleteRequest
	0, // 5: ai.v1.ModelGateway.CompleteStream:input_type -> ai.v1.CompleteRequest
	7, // 6: ai.v1.ModelGateway.Health:input_type -> ai.v1.HealthRequest
	4, // 7: ai.v1.ModelGateway.Embed:input_type -> ai.v1.EmbedRequest
	1, // 8: ai.v1.ModelGateway.Complete:output_type -> ai.v1.CompleteResponse
	2, // 9: ai.v1.ModelGateway.CompleteStream:output_type -> ai.v1.CompleteChunk
	8, // 10: ai.v1.ModelGateway.Health:output_type -> ai.v1.HealthResponse
	6, // 11: ai.v1.ModelGateway.Embed:output_type -> ai.v1.EmbedResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ai_v1_model_gateway_proto_init() }
func file_ai_v1_model_gateway_proto_init() {
	if File_ai_v1_model_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_v1_model_gateway_proto_rawDesc), len(file_ai_v1_model_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_v1_model_gateway_proto_goTypes,
		DependencyIndexes: file_ai_v1_model_gateway_proto_depIdxs,
		MessageInfos:      file_ai_v1_model_gateway_proto_msgTypes,
	}.Build()
	File_ai_v1_model_gateway_proto = out.File
	file_ai_v1_model_gateway_proto_goTypes = nil
	file_ai_v1_model_gateway_proto_depIdxs = nil
}
